In [1]:
# pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [1]:
paragraph = """By 55,000 years ago, the first modern humans, or Homo sapiens, had arrived on the Indian subcontinent from Africa, where they had earlier evolved.[27][28][29] The earliest known modern human remains in South Asia date to about 30,000 years ago.[27] After 6500 BCE, evidence for domestication of food crops and animals, construction of permanent structures, and storage of agricultural surplus appeared in Mehrgarh and other sites in Balochistan, Pakistan.[83] These gradually developed into the Indus Valley Civilisation,[84][83] the first urban culture in South Asia,[85] which flourished during 2500–1900 BCE in Pakistan and western India.[86] Centred around cities such as Mohenjo-daro, Harappa, Dholavira, and Kalibangan, and relying on varied forms of subsistence, the civilisation engaged robustly in crafts production and wide-ranging trade.[85]

During the period 2000–500 BCE, many regions of the subcontinent transitioned from the Chalcolithic cultures to the Iron Age ones.[87] The Vedas, the oldest scriptures associated with Hinduism,[88] were composed during this period,[89] and historians have analysed these to posit a Vedic culture in the Punjab region and the upper Gangetic Plain.[87] Most historians also consider this period to have encompassed several waves of Indo-Aryan migration into the subcontinent from the north-west.[88] The caste system, which created a hierarchy of priests, warriors, and free peasants, but which excluded indigenous peoples by labelling their occupations impure, arose during this period.[90] On the Deccan Plateau, archaeological evidence from this period suggests the existence of a chiefdom stage of political organisation.[87] In South India, a progression to sedentary life is indicated by the large number of megalithic monuments dating from this period,[91] as well as by nearby traces of agriculture, irrigation tanks, and craft traditions.[91]
"""

In [2]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
# libreries to use in nlp

In [3]:
# tokkenization - convert para to sentenes
# nltk.download('punkt')
sentences = nltk.sent_tokenize(paragraph)

In [4]:
stemmer = PorterStemmer()

In [5]:
from nltk.stem import WordNetLemmatizer

In [6]:
lemmetizer = WordNetLemmatizer()

In [7]:
# nltk.download('wordnet')

In [11]:
# re - regular expression
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]',' ',sentences[i])
    # used to replace the special char
    review = review.lower()
    # review = review.split()
    corpus.append(review)

In [12]:
# nltk.download('stopwords')

In [13]:
# # lemmatization
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmetizer.lemmatize(word))


year
ago
first
modern
human
homo
sapiens
arrived
indian
subcontinent
africa
earlier
evolved
earliest
known
modern
human
remains
south
asia
date
year
ago
bce
evidence
domestication
food
crop
animal
construction
permanent
structure
storage
agricultural
surplus
appeared
mehrgarh
site
balochistan
pakistan
gradually
developed
indus
valley
civilisation
first
urban
culture
south
asia
flourished
bce
pakistan
western
india
centred
around
city
mohenjo
daro
harappa
dholavira
kalibangan
relying
varied
form
subsistence
civilisation
engaged
robustly
craft
production
wide
ranging
trade
period
bce
many
region
subcontinent
transitioned
chalcolithic
culture
iron
age
one
veda
oldest
scripture
associated
hinduism
composed
period
historian
analysed
posit
vedic
culture
punjab
region
upper
gangetic
plain
historian
also
consider
period
encompassed
several
wave
indo
aryan
migration
subcontinent
north
west
caste
system
created
hierarchy
priest
warrior
free
peasant
excluded
indigenous
people
labelling
occupation

In [16]:
# # STOPWORDS ,lemmatization
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]',' ',sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmetizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
# corpus

In [20]:
# BOW -bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
# for binary,like if there is 2 the n we will count itas 1
cv = CountVectorizer(binary=True,ngram_range=(2,3))
x = cv.fit_transform(corpus)

In [ ]:
# cv = CountVectorizer(binary=True,ngram_range=(3,3))
# trigram
#  'indian subcontinent': 136,
#  'subcontinent africa': 247,

In [37]:
# cv = CountVectorizer(binary=True,ngram_range=(2,3))
# both tri and bi
#  'sapiens arrived': 226,
 # 'arrived indian': 22,
 # 'indian subcontinent': 136,
 # 'subcontinent africa': 247,


# her more sparsity,dim r more

In [40]:
# cv.vocabulary_

In [41]:
x[0].toarray()
# here more sparsity,dim r more fro (2,3)

array([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1]], dtype=int64)

In [42]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
cv = TfidfVectorizer()
x = cv.fit_transform(corpus)

In [44]:
corpus[0]

'year ago first modern human homo sapiens arrived indian subcontinent africa earlier evolved'

In [45]:
x[0]

<1x137 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [46]:
x[0].toarray()

array([[0.29796609, 0.        , 0.25589674, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.29796609, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.29796609, 0.        ,
        0.        , 0.        , 0.        , 0.29796609, 0.        ,
        0.        , 0.25589674, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.29796609, 0.25589674, 0.        ,
        0.        , 0.29796609, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [52]:
# ngrams
cvv = TfidfVectorizer(ngram_range=(3,3))
y = cvv.fit_transform(corpus)
y[0].toarray()

array([[0.30151134, 0.30151134, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.30151134, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.30151134, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.30151134, 0.30151134, 0.        , 0.        , 0.        ,
        0.30151134, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [51]:
# cvv.vocabulary_

In [61]:
# max feature
# it mean top 10 frequncy only takken for matrix
cv_max = TfidfVectorizer(ngram_range=(1,1),max_features=10)
y_max = cv_max.fit_transform(corpus)
y_max[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.59972576, 0.        , 0.        , 0.52977168, 0.59972576]])

In [62]:
cv_max.vocabulary_

{'year': 9,
 'first': 5,
 'subcontinent': 8,
 'south': 7,
 'bce': 0,
 'evidence': 4,
 'civilisation': 1,
 'culture': 3,
 'craft': 2,
 'period': 6}