In [2]:
import tensorflow as tf

In [4]:
print(("veraion: {0}").format(tf.__version__))

veraion: 2.13.0


In [5]:
a = tf.constant([[4,3],[5,6]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 6]])>

In [6]:
b = tf.Variable([[7,8],[3,4]])
b

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[7, 8],
       [3, 4]])>

In [9]:
# concatenate row
ab_concate = tf.concat(values=[a,b],axis=0)
ab_concate

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 6],
       [7, 8],
       [3, 4]])>

In [10]:
# concatenate col
ab_concate = tf.concat(values=[a,b],axis=1)
ab_concate

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [5, 6, 3, 4]])>

In [11]:
tensor_zero = tf.zeros(shape=[3,4])
tensor_zero

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [13]:
tensor = tf.zeros(shape=[3,4],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

### dtype
it is given because ,we want to run the code on any comp,like it should match

In [15]:
tensor_ones = tf.ones(shape=[3,4],dtype=tf.int32)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [19]:
tensor_ramdom = tf.random.uniform(shape=[3,4],dtype=tf.float32)
tensor_ramdom

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.83026505, 0.13255262, 0.555061  , 0.9477439 ],
       [0.89108944, 0.5496248 , 0.03233242, 0.50608027],
       [0.85777175, 0.7618818 , 0.3560524 , 0.8176762 ]], dtype=float32)>

In [16]:
reshape_tensor = tf.reshape(tensor=tensor_ones,shape=[4,3])
reshape_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [20]:
reshape_tensor_random = tf.reshape(tensor=tensor_ramdom,shape=[4,3])
reshape_tensor_random

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.83026505, 0.13255262, 0.555061  ],
       [0.9477439 , 0.89108944, 0.5496248 ],
       [0.03233242, 0.50608027, 0.85777175],
       [0.7618818 , 0.3560524 , 0.8176762 ]], dtype=float32)>

## typecast a tenso

In [23]:
tensor_float = tf.constant([[4.5,6.7],[1.2,2.3],[3.4,5.6],[7.8,9.9]],dtype=tf.float16)
tensor_int = tf.cast(tensor_float,tf.int16)
print(tensor_float)
print(tensor_int)

tf.Tensor(
[[4.5 6.7]
 [1.2 2.3]
 [3.4 5.6]
 [7.8 9.9]], shape=(4, 2), dtype=float16)
tf.Tensor(
[[4 6]
 [1 2]
 [3 5]
 [7 9]], shape=(4, 2), dtype=int16)


In [25]:
a_t = tf.transpose(tensor_int)
a_t

<tf.Tensor: shape=(2, 4), dtype=int16, numpy=
array([[4, 1, 3, 7],
       [6, 2, 5, 9]], dtype=int16)>

In [30]:
# matrix multiplication of tensors
a = tf.constant([[5,8],[3,9]])

# vector
v = tf.constant([[4],[2]])

av=tf.matmul(a,v)
av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [31]:
# element-wish multipliction
av = tf.multiply(a,v)
av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]])>

In [36]:
a = tf.constant([[4,9],[5,6],[1,8]])
rows , col = a.shape
print("rows : ",rows,"col : ",col)

# a.shape - is a numpy 

rows :  3 col :  2


In [37]:
# making an identity matrix
a_identity = tf.eye(num_rows=rows,
                    num_columns=col,
                    dtype=tf.int32)
a_identity

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>